apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: instabug
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/Volumes/postgres"
