apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: instabug
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
   path: "/mnt/data/redis"
