 apiVersion: v1
 kind: Secret
 metadata:
  name: shared-secret
  namespace: instabug
 type: Opaque
 data:
    SECRET_TOKEN: V2E0S2R1NmhNdDN0WUttNGpiOXA0dlpVdWM3akJWRncK
    DATABASE_URL: cG9zdGdyZXNxbDovL2Rya2lxOnRlc3RfZGJfcGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9kcmtpcT9lbmNvZGluZz11dGY4JnBvb2w9NSZ0aW1lb3V0PTUwMDAK
