apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-configmap
  namespace: instabug
data:
  USER_ID: "1000"
  GROUP_ID: "1000"
  WORKER_PROCESSES: "1"
  LISTEN_ON: "0.0.0.0:8010"
  CACHE_URL: "redis://redis:6379/0"
  JOB_WORKER_URL: "redis://redis:6379/0"
