apiVersion: apps/v1
kind: Deployment
metadata:
  name: drkiq-deployment
  namespace: instabug
  labels:
   tier: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      tier: backend
      app: drkiq

  template:
    metadata:
      name: postgres-pod
      namespace: instabug
      labels:
        tier: backend
        app: drkiq
    spec:
      containers:
        - name: drkiq
          image: nohierhassan/dockerizing-ruby-drkiq:v13
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          envFrom:
            - secretRef:
                name: shared-secret
            - configMapRef:
                name: shared-configmap
          ports:
            - containerPort: 8010

