apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: instabug
  labels:
   tier: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx-pod
      namespace: instabug
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nohierhassan/dockerizing-ruby-nginx:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8020
