apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-deployment
  namespace: instabug
  labels:
   tier: backend


spec:
  replicas: 1

  selector:
    matchLabels:
      tier: backend
      app: sidekiq

  template:
    metadata:
      name: sidekiq-deployment
      namespace: instabug
      labels:
       tier: backend
       app: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: nohierhassan/dockerizing-ruby-drkiq:latest
          envFrom:
            - configMapRef:
                name: shared-configmap
            - secretRef:
                name: shared-secret

