apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: instabug
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8020
      nodePort: 30000
